version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: mfasys-postgres
    restart: always
    environment:
      POSTGRES_USER: mfasys_user
      POSTGRES_PASSWORD: 123password!
      POSTGRES_DB: mfasys_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: mfasys-redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mfasys-rabbitmq
    restart: always
    ports:
      - "5672:5672"    # Messaging port
      - "15672:15672"  # Management dashboard
    environment:
      RABBITMQ_DEFAULT_USER: mfasys_user
      RABBITMQ_DEFAULT_PASS: 123password!

volumes:
  pgdata:
